# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 14:47
from __future__ import unicode_literals

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
    ]
