# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', 'user'), ('bot', 'bot'), ('admin', 'admin')], default='user', max_length=32),
        ),
    ]
